# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NBQA.ui'
#
# Created: Thu Aug  9 18:12:58 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 857)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vLayoutLeft = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.vLayoutLeft.setObjectName("vLayoutLeft")
        self.hLayoutNodeOp = QtWidgets.QHBoxLayout()
        self.hLayoutNodeOp.setObjectName("hLayoutNodeOp")
        self.btnAddNode = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAddNode.setObjectName("btnAddNode")
        self.hLayoutNodeOp.addWidget(self.btnAddNode)
        self.btnRemoveNode = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRemoveNode.setObjectName("btnRemoveNode")
        self.hLayoutNodeOp.addWidget(self.btnRemoveNode)
        self.btnClearNodeList = QtWidgets.QPushButton(self.layoutWidget)
        self.btnClearNodeList.setObjectName("btnClearNodeList")
        self.hLayoutNodeOp.addWidget(self.btnClearNodeList)
        self.vLayoutLeft.addLayout(self.hLayoutNodeOp)
        self.nodeList = QtWidgets.QListWidget(self.layoutWidget)
        self.nodeList.setObjectName("nodeList")
        self.vLayoutLeft.addWidget(self.nodeList)
        self.btnDoCheck = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDoCheck.setObjectName("btnDoCheck")
        self.vLayoutLeft.addWidget(self.btnDoCheck)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.vLayoutRight = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.vLayoutRight.setContentsMargins(0, 0, 0, 0)
        self.vLayoutRight.setObjectName("vLayoutRight")
        self.labelTitle = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.vLayoutRight.addWidget(self.labelTitle)
        self.labelDesc = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.labelDesc.setFont(font)
        self.labelDesc.setTextFormat(QtCore.Qt.RichText)
        self.labelDesc.setWordWrap(True)
        self.labelDesc.setObjectName("labelDesc")
        self.vLayoutRight.addWidget(self.labelDesc)
        self.objectList = QtWidgets.QListWidget(self.layoutWidget1)
        self.objectList.setObjectName("objectList")
        self.vLayoutRight.addWidget(self.objectList)
        self.hLayoutFixOp = QtWidgets.QHBoxLayout()
        self.hLayoutFixOp.setObjectName("hLayoutFixOp")
        self.btnFixSelect = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnFixSelect.setObjectName("btnFixSelect")
        self.hLayoutFixOp.addWidget(self.btnFixSelect)
        self.btnFixAll = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnFixAll.setObjectName("btnFixAll")
        self.hLayoutFixOp.addWidget(self.btnFixAll)
        self.vLayoutRight.addLayout(self.hLayoutFixOp)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 2))
        self.progressBar.setBaseSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 26))
        self.menubar.setObjectName("menubar")
        self.menuCreatePrj = QtWidgets.QMenu(self.menubar)
        self.menuCreatePrj.setObjectName("menuCreatePrj")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionUsage = QtWidgets.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuCreatePrj.addAction(self.actionNew)
        self.menuCreatePrj.addAction(self.actionLoad)
        self.menuCreatePrj.addSeparator()
        self.menuCreatePrj.addAction(self.actionSave)
        self.menuCreatePrj.addAction(self.actionSaveAs)
        self.menuCreatePrj.addSeparator()
        self.menuCreatePrj.addAction(self.actionDelete)
        self.menuCreatePrj.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuCreatePrj.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "NBQA 2018.08.08.01 by Jason.Li", None, -1))
        self.btnAddNode.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.btnRemoveNode.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.btnClearNodeList.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.btnDoCheck.setText(QtWidgets.QApplication.translate("MainWindow", "Start Checking", None, -1))
        self.labelTitle.setText(QtWidgets.QApplication.translate("MainWindow", "Current Check Node", None, -1))
        self.labelDesc.setText(QtWidgets.QApplication.translate("MainWindow", "check node desc; check node desc; check node desc;check node desc; check node desc; check node desc;", None, -1))
        self.btnFixSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Fix Selected", None, -1))
        self.btnFixAll.setText(QtWidgets.QApplication.translate("MainWindow", "Fix All", None, -1))
        self.menuCreatePrj.setTitle(QtWidgets.QApplication.translate("MainWindow", "Project", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionDelete.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionSaveAs.setText(QtWidgets.QApplication.translate("MainWindow", "SaveAs", None, -1))
        self.actionUsage.setText(QtWidgets.QApplication.translate("MainWindow", "Usage", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

